default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch
      - id: check-yaml
        args:
          - '--unsafe'
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/commitizen-tools/commitizen'
    rev: v3.29.0
    hooks:
      - id: commitizen
  - repo: local
    hooks:
      - id: codespell
        name: codespell
        entry: pdm run codespell
        types:
          - text
        language: system
        pass_filenames: false
        stages:
          - pre-commit
      - id: lint
        name: lint
        entry: pdm run lint
        types:
          - python
        language: system
        pass_filenames: false
        stages:
          - pre-commit
      - id: typecheck
        name: typecheck
        entry: pdm run typecheck
        types:
          - python
        language: system
        pass_filenames: false
        stages:
          - pre-commit
      - id: test
        name: test
        entry: pdm run test-cov
        language: system
        stages: [pre-push]
        pass_filenames: false
